CREATE TABLE IF NOT EXISTS inpatient_discharges (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_row_hash CHAR(64) NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    source_row_number BIGINT UNSIGNED NOT NULL,
    hospital_service_area VARCHAR(100) NULL,
    hospital_county VARCHAR(100) NULL,
    operating_certificate_number VARCHAR(30) NULL,
    permanent_facility_id VARCHAR(30) NULL,
    facility_name VARCHAR(255) NOT NULL,
    is_facility_redacted TINYINT(1) NOT NULL DEFAULT 0,
    age_group VARCHAR(30) NULL,
    age_group_sort TINYINT UNSIGNED NULL,
    zip_code_3 VARCHAR(10) NULL,
    zip_region_type VARCHAR(30) NULL,
    gender VARCHAR(30) NULL,
    race VARCHAR(100) NULL,
    ethnicity VARCHAR(100) NULL,
    length_of_stay DECIMAL(10, 2) NOT NULL,
    type_of_admission VARCHAR(50) NULL,
    emergency_department_indicator CHAR(1) NULL,
    patient_disposition VARCHAR(100) NULL,
    disposition_group VARCHAR(50) NULL,
    discharge_year SMALLINT UNSIGNED NOT NULL,
    ccsr_diagnosis_code VARCHAR(30) NOT NULL,
    ccsr_diagnosis_description VARCHAR(500) NULL,
    ccsr_procedure_code VARCHAR(30) NULL,
    ccsr_procedure_description VARCHAR(500) NULL,
    apr_drg_code VARCHAR(30) NULL,
    apr_drg_description VARCHAR(500) NULL,
    apr_mdc_code VARCHAR(30) NULL,
    apr_mdc_description VARCHAR(500) NULL,
    apr_severity_code TINYINT UNSIGNED NULL,
    apr_severity_description VARCHAR(50) NULL,
    apr_risk_of_mortality TINYINT UNSIGNED NULL,
    apr_medical_surgical_description VARCHAR(50) NULL,
    payment_typology_1 VARCHAR(100) NULL,
    payment_typology_2 VARCHAR(100) NULL,
    payment_typology_3 VARCHAR(100) NULL,
    birth_weight DECIMAL(10, 2) NULL,
    total_charges DECIMAL(16, 2) NULL,
    total_costs DECIMAL(16, 2) NULL,
    charge_cost_gap DECIMAL(16, 2) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_row_hash (source_row_hash),
    KEY idx_discharge_year (discharge_year),
    KEY idx_facility_id (permanent_facility_id),
    KEY idx_diagnosis_code (ccsr_diagnosis_code),
    KEY idx_mdc_code (apr_mdc_code),
    KEY idx_county (hospital_county),
    KEY idx_payment_typology_1 (payment_typology_1),
    KEY idx_emergency_indicator (emergency_department_indicator)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
